import { useEffect, useState } from "react";
import { Image, Sparkles } from "lucide-react";
import { DEFAULT_BACKEND_URL } from "@/lib/backendCommandClient";
import { getImageGenerationHealth, getImageHistory, getImageJobs, queueImageGeneration } from "@/lib/backendAssistantClient";

export function ImageGenerationPanel() {
  const [prompt, setPrompt] = useState("");
  const [ready, setReady] = useState(false);
  const [enabled, setEnabled] = useState(false);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("Checking optional image provider...");
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [jobs, setJobs] = useState<Array<{ id: string; status: string; prompt: string; image_url?: string | null }>>([]);
  const [history, setHistory] = useState<Array<{ id: string; image_url: string; created_at: string }>>([]);

  const refreshJobs = () => {
    getImageJobs().then((result) => {
      setJobs(result.jobs);
      const completed = result.jobs.find((job) => job.status === "completed" && job.image_url);
      if (completed?.image_url) setImageUrl(`${DEFAULT_BACKEND_URL}${completed.image_url}`);
    }).catch(() => undefined);
    getImageHistory().then((result) => setHistory(result.images)).catch(() => undefined);
  };

  useEffect(() => {
    getImageGenerationHealth()
      .then((health) => {
        setReady(health.available);
        setEnabled(health.enabled);
        setMessage(health.message);
      })
      .catch(() => setMessage("Start the backend to use image generation."));
    refreshJobs();
    const timer = window.setInterval(refreshJobs, 3000);
    return () => window.clearInterval(timer);
  }, []);

  const generate = async () => {
    if (!prompt.trim() || busy) return;
    setBusy(true);
    setImageUrl(null);
    try {
      const response = await queueImageGeneration(prompt.trim());
      setMessage(response.message || (response.queued ? "Image job queued." : "Image could not be queued."));
      if (response.queued) { setPrompt(""); refreshJobs(); }
    } catch (err) {
      setMessage(err instanceof Error ? err.message : "Image generation failed.");
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="nx-card image-generation-card">
      <div className="nx-card-head">
        <div className="nx-card-title"><Image /> AI Image Studio</div>
        <span className={`nx-list-badge ${ready && enabled ? "ok" : "mid"}`}>
          {ready && enabled ? "Ready" : "Optional"}
        </span>
      </div>
      <p className="image-generation-copy">
        Confirmed prompts use your configured Hugging Face provider. Generated files remain inside Nexa's local data folder.
      </p>
      <div className="youtube-command-row">
        <Sparkles size={16} />
        <input
          value={prompt}
          onChange={(event) => setPrompt(event.target.value)}
          placeholder="Describe the image you want..."
          onKeyDown={(event) => {
            if (event.key === "Enter") void generate();
          }}
        />
        <button type="button" className="nx-btn primary" onClick={() => void generate()} disabled={busy || !prompt.trim() || !ready || !enabled}>
          {busy ? "Generating..." : "Generate"}
        </button>
      </div>
      <p className="youtube-control-message">{message}</p>
      {imageUrl && <img className="image-generation-preview" src={imageUrl} alt={prompt} />}
      {jobs.length > 0 && <div className="image-job-list">{jobs.slice(0, 4).map((job) => <span key={job.id}>{job.prompt.slice(0, 48)} <strong>{job.status}</strong></span>)}</div>}
      {history.length > 0 && <div className="image-gallery">{history.slice(0, 6).map((item) => <img key={item.id} src={`${DEFAULT_BACKEND_URL}${item.image_url}`} alt="Generated by Nexa" onClick={() => setImageUrl(`${DEFAULT_BACKEND_URL}${item.image_url}`)} />)}</div>}
    </section>
  );
}
